language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker build -t reverseproxy ./project/reverseproxy
  - docker tag udagram-api-feed kinggeorge1/udagram-api-feed:v2
  - docker tag udagram-api-user kinggeorge1/udagram-api-user:v2
  - docker tag udagram-frontend kinggeorge1/udagram-frontend:v4
  - docker tag reverseproxy kinggeorge1/reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kinggeorge1/udagram-api-feed:v2
  - docker push kinggeorge1/udagram-api-user:v2
  - docker push kinggeorge1/udagram-frontend:v5
  - docker push kinggeorge1/reverseproxy:v2
